export const projectArray = [
  {
    project_name: "PizzWorld (in progress...)",
    project_type: "Website",
    img_href: "/projectsImage/pizzworld.png",
    type: "Website",
    event: "Side Project",
    year: 2024,
    github_link: "https://github.com/AcePeQ/Pizza-App",
    page_link: "",
    description: "",
    technologies: [
      { label: "HTML", src: "/svgIcons/html.svg" },
      { label: "CSS", src: "/svgIcons/css.svg" },
      { label: "JavaScript", src: "/svgIcons/js.svg" },
      { label: "React", src: "/svgIcons/react.svg" },
      { label: "TypeScript", src: "/svgIcons/typescript.svg" },
      { label: "Node JS", src: "/svgIcons/nodejs-2.svg" },
      { label: "Express", src: "/svgIcons/express.svg" },
      { label: "Mongo DB", src: "/svgIcons/mongodb.svg" },
      { label: "Tailwind CSS", src: "/svgIcons/tailwind.svg" },
    ],
  },
  {
    project_name: "NetWatch",
    project_type: "Website",
    img_href: "/projectsImage/netwatch.png",
    type: "Website",
    event: "College Project",
    year: 2024,
    github_link: "https://github.com/AcePeQ/Movie-App-NETwatch",
    page_link: "",
    description: "",
    technologies: [
      { label: "HTML", src: "/svgIcons/html.svg" },
      { label: "CSS", src: "/svgIcons/css.svg" },
      { label: "JavaScript", src: "/svgIcons/js.svg" },
      { label: "React", src: "/svgIcons/react.svg" },
      { label: "TypeScript", src: "/svgIcons/typescript.svg" },
    ],
  },
  {
    project_name: "Sportowi Fanatycy",
    project_type: "Website",
    img_href: "/projectsImage/fanatycy.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link: "https://github.com/Axlii50/SportowiFanatycy-WebPage",
    page_link: "https://sportowifanatycy.pl/",
    description: "",
    technologies: [{ label: "HTML", src: "/svgIcons/html.svg" }],
  },
  {
    project_name: "WOAS - Vulcanization",
    project_type: "Website",
    img_href: "/projectsImage/woas.png",
    type: "Website",
    event: "Side Project",
    year: 2024,
    github_link: "https://github.com/AcePeQ/car-service",
    page_link: "https://woas-vulcanization.netlify.app/",
    description: "",
    technologies: [{ label: "HTML", src: "/svgIcons/html.svg" }],
  },
  {
    project_name: "Portfolio",
    project_type: "Website",
    img_href: "/projectsImage/portfolio.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link: "https://github.com/AcePeQ/Portfolio/tree/main/Portfolio",
    page_link: "",
    description: "",
    technologies: [{ label: "HTML", src: "/svgIcons/html.svg" }],
  },
  {
    project_name: "Solar System",
    project_type: "Website",
    img_href: "/projectsImage/solarsystem.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link:
      "https://github.com/AcePeQ/ThreeJsPlayground/tree/main/MyOwnSolarSystem",
    page_link: "https://solar-system-project-myown.netlify.app/",
    description: "",
    technologies: [{ label: "HTML", src: "/svgIcons/html.svg" }],
  },
  {
    project_name: "Simple 3D Platform",
    project_type: "Website",
    img_href: "/projectsImage/platformProject.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link:
      "https://github.com/AcePeQ/ThreeJsPlayground/tree/main/TreeProject",
    page_link: "https://threejs-platform-project.netlify.app/",
    description: "",
    technologies: [{ label: "HTML", src: "/svgIcons/html.svg" }],
  },
  {
    project_name: "League of Legends - Quiz",
    project_type: "Website",
    img_href: "/projectsImage/lolquiz.png",
    type: "Website",
    event: "Side Project",
    year: 2024,
    github_link: "https://github.com/AcePeQ/LOLQuiz",
    page_link: "",
    description: "",
    technologies: [{ label: "HTML", src: "/svgIcons/html.svg" }],
  },
];
