export const projectArray = [
  {
    project_name: "UnsplashBox",
    project_type: "Website",
    img_href: "/projectsImage/unsplash.jpg",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link: "https://github.com/AcePeQ/UnsplashBox---Unsplash-copy",
    page_link: "https://unsplashbox-frontend.onrender.com/",
    description:
      "UnsplashBox - a full-stack project where I built a service that allows users to register and create personal collections of Unsplash images. Users can browse and add images to their curated collections, replicating functionality similar to Unsplash's own collections feature. This project showcases my full-stack development skills, including user authentication, image management, and responsive UI. The design was provided by DevChallenges.io; all coding was done by me.",
    technologies: [
      { label: "HTML", src: "/svgIcons/html.svg" },
      { label: "CSS", src: "/svgIcons/css.svg" },
      { label: "JavaScript", src: "/svgIcons/js.svg" },
      { label: "React", src: "/svgIcons/react.svg" },
      { label: "TypeScript", src: "/svgIcons/typescript.svg" },
      { label: "Node JS", src: "/svgIcons/nodejs-2.svg" },
      { label: "Express", src: "/svgIcons/express.svg" },
      { label: "Mongo DB", src: "/svgIcons/mongodb.svg" },
    ],
    technologiesUsed: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "TypeScript",
      "Node JS",
      "Express",
      "Mongo DB",
    ],
  },

  {
    project_name: "PizzWorld",
    project_type: "Website",
    img_href: "/projectsImage/pizzworld.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link: "https://github.com/AcePeQ/Pizza-App",
    page_link: "https://pizza-app-front-end.onrender.com/",
    description:
      "PizzWorld is an innovative pizza ordering platform that removes borders and lets you enjoy your favorite flavors wherever you are. Whether you're traveling, living abroad, or simply craving a pizza from another country – PizzWorld gives you access to order it no matter where you are.",
    technologies: [
      { label: "HTML", src: "/svgIcons/html.svg" },
      { label: "CSS", src: "/svgIcons/css.svg" },
      { label: "JavaScript", src: "/svgIcons/js.svg" },
      { label: "React", src: "/svgIcons/react.svg" },
      { label: "TypeScript", src: "/svgIcons/typescript.svg" },
      { label: "Node JS", src: "/svgIcons/nodejs-2.svg" },
      { label: "Express", src: "/svgIcons/express.svg" },
      { label: "Mongo DB", src: "/svgIcons/mongodb.svg" },
      { label: "Tailwind CSS", src: "/svgIcons/tailwind.svg" },
    ],
    technologiesUsed: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "TypeScript",
      "Node JS",
      "Express",
      "Mongo DB",
      "Tailwind CSS",
    ],
  },
  {
    project_name: "NETwatch",
    project_type: "Website",
    img_href: "/projectsImage/netwatch.png",
    type: "Website",
    event: "College Project",
    year: 2024,
    github_link: "https://github.com/AcePeQ/Movie-App-NETwatch",
    page_link: "",
    description:
      "NETwatch is a comprehensive platform where you can browse, search, and manage film productions with ease. Whether you are a fan of movies, TV series, or anime, NETwatch provides a seamless experience to keep track of everything you watch. By registering, you unlock personalized features, including watchlists, notifications about upcoming releases, and detailed viewing statistics. These statistics allow you to monitor how much time you've spent enjoying your favorite content. Dive into the world of entertainment and take your passion for cinema to the next level with NETwatch!",
    technologies: [
      { label: "HTML", src: "/svgIcons/html.svg" },
      { label: "CSS", src: "/svgIcons/css.svg" },
      { label: "JavaScript", src: "/svgIcons/js.svg" },
      { label: "React", src: "/svgIcons/react.svg" },
      { label: "TypeScript", src: "/svgIcons/typescript.svg" },
      { label: "C#", src: "/svgIcons/c-sharp.svg" },
    ],
    technologiesUsed: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "TypeScript",
      "C#",
    ],
  },

  {
    project_name: "Wulkanizacja WOAS",
    project_type: "Website",
    img_href: "/projectsImage/wulk-woas.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link: "https://github.com/AcePeQ/Wulkanizacja-Woas/tree/main/woas",
    page_link: "https://wulkanizacja-woas.netlify.app/",
    description:
      "This project is a website for my dad’s car service business, WOAS. It features a clear presentation of services, including tire services (vulcanization) and mobile vulcanization, which allows customers to get help on the road. The site also includes a contact section with a built-in map, making it easy to locate the workshop. Visitors can check opening hours, browse available services, and quickly get in touch. The design is modern, responsive, and focused on convenience for the customer.",
    technologies: [
      { label: "HTML", src: "/svgIcons/html.svg" },
      { label: "CSS", src: "/svgIcons/css.svg" },
      { label: "JavaScript", src: "/svgIcons/js.svg" },
      { label: "React", src: "/svgIcons/react.svg" },
      { label: "TypeScript", src: "/svgIcons/typescript.svg" },
    ],
    technologiesUsed: ["HTML", "CSS", "JavaScript", "React", "TypeScript"],
  },

  {
    project_name: "Simple Translate App",
    project_type: "Website",
    img_href: "/projectsImage/translateapp.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link: "https://github.com/AcePeQ/translate-app",
    page_link: "https://simple-translate-appmn.netlify.app/",
    description:
      "Simple Translate App is a project prepared by devChallenges.io. I had to create application that includes features such as: text-to-speach, copy to copyboard and automatic language detection based on the input message. The application seemes simple but it's quite challenging to implement due to many feature. Thanks to this project I learned how to work with build-in Speech Synthesis and Speech Synthesis Utterance features.",
    technologies: [
      { label: "HTML", src: "/svgIcons/html.svg" },
      { label: "CSS", src: "/svgIcons/css.svg" },
      { label: "JavaScript", src: "/svgIcons/js.svg" },
      { label: "React", src: "/svgIcons/react.svg" },
      { label: "TypeScript", src: "/svgIcons/typescript.svg" },
    ],
    technologiesUsed: ["HTML", "CSS", "JavaScript", "React", "TypeScript"],
  },
  {
    project_name: "Sportowi Fanatycy",
    project_type: "Website",
    img_href: "/projectsImage/fanatycy.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link: "https://github.com/Axlii50/SportowiFanatycy-WebPage",
    page_link: "",
    description:
      "Sportowi Fanatycy (Created in association with Jakub Stegienko - Axlii50) is a platform designed for sports betting enthusiasts, offering both intuitive bet management and access to expert picks. As an administrator, you can create and manage bets, providing users with valuable insights. As a user, you gain access to free daily picks from our experts, along with the option to purchase premium packages that offer even more reliable and profitable betting tips. Join us now and bet with the best!",
    technologies: [
      { label: "HTML", src: "/svgIcons/html.svg" },
      { label: "CSS", src: "/svgIcons/css.svg" },
      { label: "JavaScript", src: "/svgIcons/js.svg" },
      { label: "React", src: "/svgIcons/react.svg" },
      { label: "TypeScript", src: "/svgIcons/typescript.svg" },
      { label: "C#", src: "/svgIcons/c-sharp.svg" },
    ],
    technologiesUsed: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "TypeScript",
      "C#",
    ],
  },
  {
    project_name: "WOAS - Vulcanization",
    project_type: "Website",
    img_href: "/projectsImage/woas.png",
    type: "Website",
    event: "Side Project",
    year: 2024,
    github_link: "https://github.com/AcePeQ/car-service",
    page_link: "https://woas-vulcanization.netlify.app/",
    description:
      "Wulkanizacja Woas is a simple and user-friendly website showcasing our tire service workshop. Here, you can find detailed information about our available services and performed work, including tire replacement, wheel balancing, and tire repairs. Additionally, we provide a contact form that allows you to quickly and conveniently send us a message. Feel free to check out our services!",
    technologies: [
      { label: "HTML", src: "/svgIcons/html.svg" },
      { label: "CSS", src: "/svgIcons/css.svg" },
      { label: "JavaScript", src: "/svgIcons/js.svg" },
      { label: "React", src: "/svgIcons/react.svg" },
    ],
    technologiesUsed: ["HTML", "CSS", "JavaScript", "React"],
  },
  {
    project_name: "Portfolio",
    project_type: "Website",
    img_href: "/projectsImage/portfolio.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link: "https://github.com/AcePeQ/Portfolio/tree/main/Portfolio",
    page_link: "https://nojszewmdev.netlify.app/",
    description:
      "Welcome to my portfolio! This is where I showcase my projects, skills, and experience. Here, you’ll find examples of my work, details about my expertise, and projects I’m proud of. If you have any questions or are interested in collaboration, feel free to reach out!",
    technologies: [
      { label: "HTML", src: "/svgIcons/html.svg" },
      { label: "CSS", src: "/svgIcons/css.svg" },
      { label: "JavaScript", src: "/svgIcons/js.svg" },
      { label: "React", src: "/svgIcons/react.svg" },
      { label: "TypeScript", src: "/svgIcons/typescript.svg" },
    ],
    technologiesUsed: ["HTML", "CSS", "JavaScript", "React", "TypeScript"],
  },
  {
    project_name: "Solar System",
    project_type: "Website",
    img_href: "/projectsImage/solarsystem.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link:
      "https://github.com/AcePeQ/ThreeJsPlayground/tree/main/MyOwnSolarSystem",
    page_link: "https://solar-system-project-myown.netlify.app/",
    description:
      "Solar System is a project created using Three.js, showcasing our Solar System in a 3D space. The project displays all the planets and the Sun, allowing interactive 3D viewing. Animation techniques were used to make the planets move around the Sun in realistic orbits. The goal of the project was to demonstrate the capabilities of Three.js in creating dynamic spatial models and to introduce the concept of orbital physics and 3D animation.",
    technologies: [
      { label: "HTML", src: "/svgIcons/html.svg" },
      { label: "Three.js", src: "/svgIcons/threejs.svg" },
      { label: "JavaScript", src: "/svgIcons/js.svg" },
    ],
    technologiesUsed: ["HTML", "Three.js", "JavaScript"],
  },
  {
    project_name: "Simple 3D Platform",
    project_type: "Website",
    img_href: "/projectsImage/platformProject.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link:
      "https://github.com/AcePeQ/ThreeJsPlayground/tree/main/TreeProject",
    page_link: "https://threejs-platform-project.netlify.app/",
    description:
      "Simple 3D Platform is my first project using Three.js, showcasing a simple yet visually appealing 3D platform. The project features realistic shadows and an additional 3D model placed at the center of the platform. The goal was to familiarize myself with the basics of Three.js and create an interactive 3D scene that demonstrates the capabilities of the library, including shadow handling and 3D model importing. This serves as a great example of using fundamental rendering techniques in a 3D environment.",
    technologies: [
      { label: "HTML", src: "/svgIcons/html.svg" },
      { label: "Three.js", src: "/svgIcons/threejs.svg" },
      { label: "JavaScript", src: "/svgIcons/js.svg" },
    ],
    technologiesUsed: ["HTML", "Three.js", "JavaScript"],
  },
  {
    project_name: "League of Legends - Quiz",
    project_type: "Website",
    img_href: "/projectsImage/lolquiz.png",
    type: "Website",
    event: "Side Project",
    year: 2024,
    github_link: "https://github.com/AcePeQ/LOLQuiz",
    page_link: "",
    description:
      "League of Legends - Quiz is an interactive quiz designed for fans of the game to test their knowledge of one of the most popular MOBA games. The quiz features a series of questions related to the game, champions, items, and mechanics. With a built-in point tracker, you'll be able to monitor your score in real time. Once the quiz is finished, you’ll receive detailed statistics that show how well you performed across different categories. Additionally, there is a countdown timer that keeps track of the time remaining. Take the challenge and see how well you know the world of League of Legends!",
    technologies: [
      { label: "HTML", src: "/svgIcons/html.svg" },
      { label: "CSS", src: "/svgIcons/css.svg" },
      { label: "JavaScript", src: "/svgIcons/js.svg" },
      { label: "React", src: "/svgIcons/react.svg" },
    ],
    technologiesUsed: ["HTML", "CSS", "JavaScript", "React"],
  },
];
