export const projectArray = [
  {
    project_name: "PizzWorld (in progress...)",
    project_type: "Website",
    img_href: "/public/projectImage/pizzworld.png",
    type: "Website",
    event: "Side Project",
    year: 2024,
    github_link: "https://github.com/AcePeQ/Pizza-App",
    page_link: "",
    description: "",
    technologies: [{ name: "HTML", img_path: "/public/svgIcons/html.svg" }],
  },
  {
    project_name: "NetWatch",
    project_type: "Website",
    img_href: "/public/projectImage/netwatch.png",
    type: "Website",
    event: "College Project",
    year: 2024,
    github_link: "https://github.com/AcePeQ/Movie-App-NETwatch",
    page_link: "",
    description: "",
    technologies: [{ name: "HTML", img_path: "/public/svgIcons/html.svg" }],
  },
  {
    project_name: "Sportowi Fanatycy",
    project_type: "Website",
    img_href: "/public/projectImage/fanatycy.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link: "https://github.com/Axlii50/SportowiFanatycy-WebPage",
    page_link: "https://sportowifanatycy.pl/",
    description: "",
  },
  {
    project_name: "WOAS - Vulcanization",
    project_type: "Website",
    img_href: "/public/projectImage/woas.png",
    type: "Website",
    event: "Side Project",
    year: 2024,
    github_link: "https://github.com/AcePeQ/car-service",
    page_link: "https://woas-vulcanization.netlify.app/",
    description: "",
  },
  {
    project_name: "Portfolio",
    project_type: "Website",
    img_href: "/public/projectImage/portfolio.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link: "https://github.com/AcePeQ/Portfolio/tree/main/Portfolio",
    page_link: "",
    description: "",
  },
  {
    project_name: "Solar System",
    project_type: "Website",
    img_href: "/public/projectImage/solarsystem.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link:
      "https://github.com/AcePeQ/ThreeJsPlayground/tree/main/MyOwnSolarSystem",
    page_link: "https://solar-system-project-myown.netlify.app/",
    description: "",
  },
  {
    project_name: "Simple 3D Platform",
    project_type: "Website",
    img_href: "/public/projectImage/platformProject.png",
    type: "Website",
    event: "Side Project",
    year: 2025,
    github_link:
      "https://github.com/AcePeQ/ThreeJsPlayground/tree/main/TreeProject",
    page_link: "https://threejs-platform-project.netlify.app/",
    description: "",
  },
  {
    project_name: "League of Legends - Quiz",
    project_type: "Website",
    img_href: "/public/projectImage/lolquiz.png",
    type: "Website",
    event: "Side Project",
    year: 2024,
    github_link: "https://github.com/AcePeQ/LOLQuiz",
    page_link: "",
    description: "",
  },
];
